from pathlib import Path

# Standing architecture rules.
p = Path('AGENTS.md')
text = p.read_text()
old = '- Recommendation preparation must not strand playback on a one-row queue. Prewarm may run before isolation, but once an explicit Track Mix seed is isolated the Initial Size refill **must not wait for the remote Smart-DJ pool at all**: start/reuse the pool fill, let native GMMP fill immediately, and allow recommendation preparation to continue only in the background for later refills.\n'
new = old + '- On GMMP 4.2.1, `WAIT_PLAY` is still GMMP-owned playback continuity: a natural Auto-DJ refill passes through natively. Only the Track-Mix-owned `CLEARING`/`FILLING` mutation window may suppress that refill. Seed isolation preserves the naturally verified absolute Current queue position; later compaction closes position gaps around that anchor instead of forcing Current to position 1.\n'
if text.count(old) != 1:
    raise SystemExit('AGENTS Track Mix anchor mismatch')
text = text.replace(old, new, 1)
old = '- Resolve Playlist Link query-column constants by native semantic value (for example `track_uri`); historical holder and field names are fast paths only. If the holder itself is remapped, discovery may enumerate the target dex class names without initializing them, structurally filter compatible static fields, then inspect only a bounded read-only in-memory value graph. If the field object remains opaque, the already-resolved native IN predicate builder may be used only as an in-memory semantic probe; no database query or unknown method is executed. Uniqueness remains mandatory and ambiguity fails closed. Optional query capabilities must be lazy: an unproven OR-group mapping must not disable a single native-IN link, while a source that actually requires the missing group fails closed.\n'
new = '- Resolve Playlist Link query-column constants by native semantic value (for example `track_uri`); historical holder and field names are fast paths only. If the holder itself is remapped, discovery may enumerate the target dex class names without initializing them, structurally filter compatible static fields, then inspect only a bounded read-only in-memory value graph. A single class whose reflection metadata cannot be resolved on the current Android runtime (for example because one of its field types links a newer framework API) is skipped rather than aborting semantic discovery. If the field object remains opaque, the already-resolved native IN predicate builder may be used only as an in-memory semantic probe; no database query or unknown method is executed. Uniqueness remains mandatory and ambiguity fails closed. Optional query capabilities must be lazy: an unproven OR-group mapping must not disable a single native-IN link, while a source that actually requires the missing group fails closed.\n'
if text.count(old) != 1:
    raise SystemExit('AGENTS Playlist Link anchor mismatch')
p.write_text(text.replace(old, new, 1))

# Version chronology/evidence.
p = Path('docs/GMMP_COMPATIBILITY_PLAYBOOK.md')
text = p.read_text()
anchor = 'Runtime `3cf7c504dc7d` finally proved that the failure occurs one level earlier still: both historical holder classes `w75` and `z75` are rejected before any semantic `track_uri` field can be selected, while the independently proven chooser callback `as4$g.accept(...)` continues to fire. The holder names are therefore no longer a gate. They remain fast paths, but on miss the resolver enumerates only class names from the target ClassLoader\'s dex files without initializing them, limits discovery to the native query-field package and structurally compatible static fields, and requires one unique semantic match. Direct bounded in-memory value inspection remains first choice; if the query-field object is opaque, only the already resolved native IN predicate builder may be used as a read-only in-memory semantic probe. No database query or unknown method is executed, and ambiguity still fails closed. Device re-acceptance remains pending.\n'
addition = anchor + '\nRuntime `4cfe88ea5430` then exposed three independent defects in one bundled run. First, Playlist Link\'s broad semantic fallback encountered a GMMP class whose declared-field metadata referenced unavailable `android.view.ScrollFeedbackProvider`; semantic dex discovery now skips an individually uninspectable holder instead of aborting the whole resolver. Second, the remaining Track Mix null-next window occurred **before** seed isolation: while stage `WAIT_PLAY` was active GoneSmart suppressed GMMP\'s natural 4.2.1 Auto-DJ refill, and GMMP then queried a missing next queue position. `WAIT_PLAY` is now native pass-through on 4.2.1, while only `CLEARING`/`FILLING` remain held; the accepted legacy `ex3` behavior is unchanged. Third, the first Track Mix invocation had already deleted stale rows successfully and failed only when GoneSmart unnecessarily moved an already naturally Current seed from absolute position 5 to 1 through the passive Current writer. Seed isolation therefore keeps the verified absolute position, and sparse post-refill rows are compacted around that Current anchor (for example `5,11,12,13,14 -> 5,6,7,8,9`) rather than rebasing the queue to 1. Host regression tests cover these ownership/state rules; device re-acceptance remains pending.\n'
if text.count(anchor) != 1:
    raise SystemExit('playbook chronology anchor mismatch')
p.write_text(text.replace(anchor, addition, 1))

p = Path('docs/GMMP_421_COMPLETION.md')
text = p.read_text().rstrip()
entry = '- 9 October 2026: runtime `4cfe88ea5430` provided one bundled trace for all remaining observed failures. Playlist Link semantic dex discovery aborted on an unrelated holder whose field metadata linked unavailable `android.view.ScrollFeedbackProvider`; the resolver now skips individually uninspectable holders while preserving unique/fail-closed semantic matching. Track Mix showed that the null-next window began during `WAIT_PLAY`, before seed isolation, because GoneSmart held GMMP\'s natural 4.2.1 refill; that stage now passes native refill through while `CLEARING`/`FILLING` remain protected. The same run showed the new first-invocation failure occurred only after stale-row deletion, when GoneSmart unnecessarily tried to move the already naturally Current seed from absolute position 5 to 1. Seed isolation and later sparse-position compaction now preserve the verified Current anchor instead. The bundled repair is host-tested and built, but one device re-acceptance pass remains required before marking these paths accepted.'
if entry in text:
    raise SystemExit('completion evidence already present')
p.write_text(text + '\n' + entry + '\n')

print('4.2.1 regression evidence recorded.')
